{
 "title": "Monitor Ambiental Interior",
 "tags": [
  "bme680",
  "environment",
  "temperature",
  "humidity",
  "preassure"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperatura",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"temperature_c\") FROM \"environment\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"humidity_percent\") FROM \"environment\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Presión",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"pressure_hpa\") FROM \"environment\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 24, "h": 12 },
   "targets": [
    {
     "query": "SELECT mean(\"temperature_c\") FROM \"environment\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "alias": "Temperatura (°C)"
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 17, "w": 24, "h": 12 },
   "targets": [
    {
     "query": "SELECT mean(\"humidity_percent\") FROM \"environment\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "alias": "Humedad (%)"
    }
   ]
  },
  {
   "title": "Presión atmosférica",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 29, "w": 24, "h": 12 },
   "targets": [
    {
     "query": "SELECT mean(\"pressure_hpa\") FROM \"environment\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "alias": "Presión (hPa)"
    }
   ]
  }
 ]
}