apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1
  - name: InfluxDB Environment
    orgId: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUXDB_ENERGY_DB}
    isDefault: true
    editable: true
    jsonData:
      version: InfluxQL
      httpMode: GET

  - name: InfluxDB Environment
    uid: environment-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUXDB_ENV_DB}
    isDefault: false
    editable: true
    jsonData:
      version: InfluxQL
      httpMode: GET
