[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "10s"
  hostname = "raspberry-pi"
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["${INFLUX_URL}"]
  database = "${INFLUX_ENV_DB}"
  namepass = ["environment"]

[[outputs.influxdb]]
  urls = ["${INFLUX_URL}"]
  database = "${INFLUX_ENERGY_DB}"
  namepass = ["energia"]

[[inputs.mqtt_consumer]]
  servers = ["${MQTT_SERVER}"]
  topics = ["${MQTT_ENV_TOPIC}"]
  client_id = "smart-env-telegraf"
  qos = 0
  connection_timeout = "30s"
  persistent_session = false
  username = "${MQTT_USERNAME}"
  password = "${MQTT_PASSWORD}"
  topic_tag = "topic"
  data_format = "json_v2"

  [inputs.mqtt_consumer.tags]
    device = "esp32c3-supermini"
    sensor = "bme680"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "environment"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temperature_c"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "humidity_percent"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "pressure_hpa"
      type = "float"

[[inputs.mqtt_consumer]]
  servers = ["${MQTT_SERVER}"]
  topics = ["${MQTT_ENERGY_TOPIC}"]
  client_id = "smart-energy-telegraf"
  qos = 1
  connection_timeout = "30s"
  persistent_session = false
  username = "${MQTT_USERNAME}"
  password = "${MQTT_PASSWORD}"
  topic_tag = "topic"
  data_format = "json_v2"

  [inputs.mqtt_consumer.tags]
    device = "tuya-breaker"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "energia"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "voltaje_V"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "corriente_A"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "potencia_W"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "potencia_VA"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "factor_potencia"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "energia_kWh"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "alarma_sobrevoltaje"
      type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "alarma_sobrecorriente"
      type = "int"
